# Generated by Django 3.0.8 on 2020-07-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
